package servicios;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2020-02-27T11:39:54.859-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "ServicesSoapService", 
                  wsdlLocation = "file:/C:/Users/PCX/AppData/Local/Temp/tempdir3438159825782116325.tmp/ServicesSoap_1.wsdl",
                  targetNamespace = "http://servicios/") 
public class ServicesSoapService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://servicios/", "ServicesSoapService");
    public final static QName ServicesSoapPort = new QName("http://servicios/", "ServicesSoapPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/PCX/AppData/Local/Temp/tempdir3438159825782116325.tmp/ServicesSoap_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServicesSoapService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/PCX/AppData/Local/Temp/tempdir3438159825782116325.tmp/ServicesSoap_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServicesSoapService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServicesSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicesSoapService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServicesSoapService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServicesSoapService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServicesSoapService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ServicesSoap
     */
    @WebEndpoint(name = "ServicesSoapPort")
    public ServicesSoap getServicesSoapPort() {
        return super.getPort(ServicesSoapPort, ServicesSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicesSoap
     */
    @WebEndpoint(name = "ServicesSoapPort")
    public ServicesSoap getServicesSoapPort(WebServiceFeature... features) {
        return super.getPort(ServicesSoapPort, ServicesSoap.class, features);
    }

}
