package servicios1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2020-02-10T12:47:05.234-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://servicios/", name = "FacturaServiceeSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface FacturaServiceeSoap {

    @WebMethod
    @RequestWrapper(localName = "realizarRecargaFactura", targetNamespace = "http://servicios/", className = "servicios.RealizarRecargaFactura")
    @ResponseWrapper(localName = "realizarRecargaFacturaResponse", targetNamespace = "http://servicios/", className = "servicios.RealizarRecargaFacturaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public servicios1.RespuestaFac realizarRecargaFactura(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2
    );
}
