package servicios1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2020-02-10T12:47:05.255-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "FacturaServiceeSoapService", 
                  wsdlLocation = "file:/C:/Users/PCX/AppData/Local/Temp/tempdir970079758965423026.tmp/FacturaServiceeSoap_1.wsdl",
                  targetNamespace = "http://servicios/") 
public class FacturaServiceeSoapService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://servicios/", "FacturaServiceeSoapService");
    public final static QName FacturaServiceeSoapPort = new QName("http://servicios/", "FacturaServiceeSoapPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/PCX/AppData/Local/Temp/tempdir970079758965423026.tmp/FacturaServiceeSoap_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FacturaServiceeSoapService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/PCX/AppData/Local/Temp/tempdir970079758965423026.tmp/FacturaServiceeSoap_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FacturaServiceeSoapService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FacturaServiceeSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FacturaServiceeSoapService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FacturaServiceeSoapService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FacturaServiceeSoapService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FacturaServiceeSoapService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns FacturaServiceeSoap
     */
    @WebEndpoint(name = "FacturaServiceeSoapPort")
    public FacturaServiceeSoap getFacturaServiceeSoapPort() {
        return super.getPort(FacturaServiceeSoapPort, FacturaServiceeSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FacturaServiceeSoap
     */
    @WebEndpoint(name = "FacturaServiceeSoapPort")
    public FacturaServiceeSoap getFacturaServiceeSoapPort(WebServiceFeature... features) {
        return super.getPort(FacturaServiceeSoapPort, FacturaServiceeSoap.class, features);
    }

}
