
package servicios1;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2020-02-10T12:47:05.175-05:00
 * Generated source version: 2.7.18
 * 
 */
public final class FacturaServiceeSoap_FacturaServiceeSoapPort_Client {

    public static final QName SERVICE_NAME = new QName("http://servicios/", "FacturaServiceeSoapService");

    public FacturaServiceeSoap_FacturaServiceeSoapPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = FacturaServiceeSoapService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        FacturaServiceeSoapService ss = new FacturaServiceeSoapService(wsdlURL, SERVICE_NAME);
        FacturaServiceeSoap port = ss.getFacturaServiceeSoapPort();  
        
        {
        System.out.println("Invoking realizarRecargaFactura...");
        java.lang.String _realizarRecargaFactura_arg0 = "";
        int _realizarRecargaFactura_arg1 = 0;
        double _realizarRecargaFactura_arg2 = 0.0;
        servicios1.RespuestaFac _realizarRecargaFactura__return = port.realizarRecargaFactura(_realizarRecargaFactura_arg0, _realizarRecargaFactura_arg1, _realizarRecargaFactura_arg2);
        System.out.println("realizarRecargaFactura.result=" + _realizarRecargaFactura__return);


        }

        System.exit(0);
    }
    
    
    public String generarUuid () {
    	URL wsdlURL = FacturaServiceeSoapService.WSDL_LOCATION;
             
        FacturaServiceeSoapService ss = new FacturaServiceeSoapService(wsdlURL, SERVICE_NAME);
        FacturaServiceeSoap port = ss.getFacturaServiceeSoapPort();  
        
        {
        System.out.println("Invoking realizarRecargaFactura...");
        java.lang.String _realizarRecargaFactura_arg0 = "";
        int _realizarRecargaFactura_arg1 = 0;
        double _realizarRecargaFactura_arg2 = 0.0;
        servicios1.RespuestaFac _realizarRecargaFactura__return = port.realizarRecargaFactura(_realizarRecargaFactura_arg0, _realizarRecargaFactura_arg1, _realizarRecargaFactura_arg2);
        System.out.println("realizarRecargaFactura.result=" + _realizarRecargaFactura__return.mensaje);
        return _realizarRecargaFactura__return.mensaje;

        }
    }

}
