
package servicios;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2020-02-10T11:27:31.925-05:00
 * Generated source version: 2.7.18
 * 
 */
public final class MovimientoServiceSoap_MovimientoServiceSoapPort_Client {

    public static final QName SERVICE_NAME = new QName("http://servicios/", "MovimientoServiceSoapService");

    public MovimientoServiceSoap_MovimientoServiceSoapPort_Client() {
    }

    public static void main(String args[], String cedula) throws java.lang.Exception {
        URL wsdlURL = MovimientoServiceSoapService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MovimientoServiceSoapService ss = new MovimientoServiceSoapService(wsdlURL, SERVICE_NAME);
        MovimientoServiceSoap port = ss.getMovimientoServiceSoapPort();  
        
        {
        System.out.println("Invoking realizarRecarga...");
        java.lang.String _realizarRecarga_arg0 = "010";
        java.lang.String _realizarRecarga_arg1 = "010";
        double _realizarRecarga_arg2 = 0.0;
        servicios.Respuesta _realizarRecarga__return = port.realizarRecarga(_realizarRecarga_arg0, _realizarRecarga_arg1, _realizarRecarga_arg2);
        System.out.println("realizarRecarga.result=" + _realizarRecarga__return);


        }

        System.exit(0);
    }
    
    
    public int metodo(String cedula, String celular, int valor) {
    	System.out.println("Esta entrando al metodo");
    	URL wsdlURL = MovimientoServiceSoapService.WSDL_LOCATION;
        
    	 MovimientoServiceSoapService ss = new MovimientoServiceSoapService(wsdlURL, SERVICE_NAME);
         MovimientoServiceSoap port = ss.getMovimientoServiceSoapPort();  
         
         
         System.out.println("Invoking realizarRecarga...");
         java.lang.String _realizarRecarga_arg0 = cedula;
         java.lang.String _realizarRecarga_arg1 = celular;
         double _realizarRecarga_arg2 = valor;
         servicios.Respuesta _realizarRecarga__return = port.realizarRecarga(_realizarRecarga_arg0, _realizarRecarga_arg1, _realizarRecarga_arg2);
         System.out.println("realizarRecarga.result=" + _realizarRecarga__return.mensaje);
         return _realizarRecarga__return.codigo;

         
    }
}
