package servicios;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2020-02-10T11:27:31.988-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://servicios/", name = "MovimientoServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface MovimientoServiceSoap {

    @WebMethod
    @RequestWrapper(localName = "realizarRecarga", targetNamespace = "http://servicios/", className = "servicios.RealizarRecarga")
    @ResponseWrapper(localName = "realizarRecargaResponse", targetNamespace = "http://servicios/", className = "servicios.RealizarRecargaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public servicios.Respuesta realizarRecarga(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2
    );
}
