package servicios;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2020-02-10T11:27:32.010-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "MovimientoServiceSoapService", 
                  wsdlLocation = "file:/C:/Users/PCX/AppData/Local/Temp/tempdir6554590750265210037.tmp/MovimientoServiceSoap_1.wsdl",
                  targetNamespace = "http://servicios/") 
public class MovimientoServiceSoapService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://servicios/", "MovimientoServiceSoapService");
    public final static QName MovimientoServiceSoapPort = new QName("http://servicios/", "MovimientoServiceSoapPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/PCX/AppData/Local/Temp/tempdir6554590750265210037.tmp/MovimientoServiceSoap_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MovimientoServiceSoapService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/PCX/AppData/Local/Temp/tempdir6554590750265210037.tmp/MovimientoServiceSoap_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MovimientoServiceSoapService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MovimientoServiceSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MovimientoServiceSoapService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MovimientoServiceSoapService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MovimientoServiceSoapService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MovimientoServiceSoapService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns MovimientoServiceSoap
     */
    @WebEndpoint(name = "MovimientoServiceSoapPort")
    public MovimientoServiceSoap getMovimientoServiceSoapPort() {
        return super.getPort(MovimientoServiceSoapPort, MovimientoServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MovimientoServiceSoap
     */
    @WebEndpoint(name = "MovimientoServiceSoapPort")
    public MovimientoServiceSoap getMovimientoServiceSoapPort(WebServiceFeature... features) {
        return super.getPort(MovimientoServiceSoapPort, MovimientoServiceSoap.class, features);
    }

}
