
package servicios;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2020-02-27T11:39:54.794-05:00
 * Generated source version: 2.7.18
 * 
 */
public final class ServicesSoap_ServicesSoapPort_Client {
	
	
    private static final QName SERVICE_NAME = new QName("http://servicios/", "ServicesSoapService");

    private ServicesSoap_ServicesSoapPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ServicesSoapService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ServicesSoapService ss = new ServicesSoapService(wsdlURL, SERVICE_NAME);
        ServicesSoap port = ss.getServicesSoapPort();  
        
        {
        System.out.println("Invoking votar...");
        java.lang.String _votar_arg0 = "Andres";
        java.lang.String _votar_arg1 = "00000000";
        java.lang.String _votar_arg2 = "0306171325";
        servicios.Respuesta _votar__return = port.votar(_votar_arg0, _votar_arg1, _votar_arg2);
        System.out.println("votar.result=" + _votar__return.getMensaje());


        }

        System.exit(0);
    }

}
