package servicios;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2020-02-27T11:39:54.850-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://servicios/", name = "ServicesSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ServicesSoap {

    @WebMethod(operationName = "Votar")
    @RequestWrapper(localName = "Votar", targetNamespace = "http://servicios/", className = "servicios.Votar")
    @ResponseWrapper(localName = "VotarResponse", targetNamespace = "http://servicios/", className = "servicios.VotarResponse")
    @WebResult(name = "return", targetNamespace = "")
    public servicios.Respuesta votar(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );
}
